### ISSUE TITLE
new name poll

### ISSUE THREAD

**Issue by b10n1k** [qa-sle-yast/libyui_client#22]
<p><a href="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/validest/vote"><img src="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/validest" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/yats%20-%20yet%20another%20test%20system/vote"><img src="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/yats%20-%20yet%20another%20test%20system" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/yatt%20-%20yet%20another%20testing%20tool/vote"><img src="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/yatt%20-%20yet%20another%20testing%20tool" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/yakuza/vote"><img src="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/yakuza" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/requesto/vote"><img src="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/requesto" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/magia/vote"><img src="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/magia" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/miyaki/vote"><img src="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/miyaki" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/yui-integra%20%2F%20yui-ruby-integra/vote"><img src="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/yui-integra%20%2F%20yui-ruby-integra" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/libyui-restapi-client/vote"><img src="https://api.gh-polls.com/poll/01EJV1X11CRGY688076EZ3M1BC/libyui-restapi-client" alt=""></a></p>

**Comment by b10n1k** [comment]
/polls "validest" "yats - yet another test system" "yapits - yast api testing system" "yakuza" "requesto" "magia" "miyaki"

**Comment by JRivrain** [comment]
I prefer libyui-client, makes it clear what it is, even if it's boring.

**Comment by rwx788** [comment]
During the meeting we agreed to ruby-yui-rest-client as a name of the project.
